# Site settings
author: Juan Siu
title: Hello World
header-img: img/home-bg.png
email: juan.siu@gmail.com
copyright_name: Juan Siu
description: > # this means to ignore newlines until "baseurl:"
  A journey to the unknown
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  l1mk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
